server:
 port: 8080
 error:
  path: /error

logging:
  level:
   sia.tacocloud: DEBUG

   org:
     springframework:
       jdbc:
         core:
           jdbcTemplate: DEBUG

spring:
  data:
    web:
      pageable:
        default-page-size: 3
    rest:
      base-path: /data-api
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/tacocloud
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    locations: classpath:/db.migration
    schemas: tacocloud
    baseline-on-migrate: true
    baseline-version: 1
  security:
   oauth2:
     client:
      registration:
        facebook:
          client-id: 206743098891362
          client-secret: d29809d025250bba1e21da849b26234a
          redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
          client-name: Facebook
          scope:
            - email
            - public_profile








