CREATE TABLE taco
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    taco_order_id BIGINT,
    CONSTRAINT pk_taco PRIMARY KEY (id)
);
ALTER TABLE taco
    ADD CONSTRAINT fk_taco_on_taco_order FOREIGN KEY (taco_order_id) REFERENCES taco_order (id);