CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255),
    password     VARCHAR(255),
    fullname     VARCHAR(255),
    street       VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    zip          VARCHAR(255),
    phone_number VARCHAR(255),
    role_id      BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);