CREATE TABLE taco_order
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_name   VARCHAR(255),
    delivery_street VARCHAR(255),
    delivery_city   VARCHAR(255),
    delivery_state  VARCHAR(255),
    delivery_zip    VARCHAR(255),
    cc_number       VARCHAR(255),
    cc_expiration   VARCHAR(255),
    cccvv           VARCHAR(255),
    placed_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT,
    CONSTRAINT pk_taco_order PRIMARY KEY (id)
);

ALTER TABLE taco_order
    ADD CONSTRAINT FK_TACO_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);