CREATE TABLE IF NOT EXISTS ingredient
(
    id   VARCHAR(4)  NOT NULL,
    name VARCHAR(25) NOT NULL,
    type VARCHAR(10)     NOT NULL,
    CONSTRAINT pk_ingredient PRIMARY KEY (id)
);

insert into ingredient (id, name, type)
values ('FLTO', 'Flour Tortilla', 'WRAP'),
       ('COTO', 'Corn Tortilla', 'WRAP'),
       ('GRBF', 'Ground Beef', 'PROTEIN'),
       ('CARN', 'Carnitas', 'PROTEIN'),
       ('TMTO', 'Diced Tomatoes', 'VEGGIES'),
       ('LETC', 'Lettuce', 'VEGGIES'),
       ('CHED', 'Cheddar', 'CHEESE'),
       ('JACK', 'Monterrey Jack', 'CHEESE'),
       ('SLSA', 'Salsa', 'SAUCE'),
       ('SRCR', 'Sour Cream', 'SAUCE');


--  taco
CREATE TABLE taco
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    taco_order_id BIGINT,
    CONSTRAINT pk_taco PRIMARY KEY (id)
);
ALTER TABLE taco
    ADD CONSTRAINT fk_taco_on_taco_order FOREIGN KEY (taco_order_id) REFERENCES taco_order (id);

CREATE TABLE taco_ingredients
(
    taco_id        BIGINT       NOT NULL,
    ingredients_id VARCHAR(255) NOT NULL
);

ALTER TABLE taco_ingredients
    ADD FOREIGN KEY(ingredients_id) REFERENCES ingredient (id);

ALTER TABLE taco_ingredients
    ADD CONSTRAINT fk_taco_ingredients FOREIGN KEY (taco_id) REFERENCES taco (id);


--taco_order
CREATE TABLE taco_order
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_name   VARCHAR(255),
    delivery_street VARCHAR(255),
    delivery_city   VARCHAR(255),
    delivery_state  VARCHAR(255),
    delivery_zip    VARCHAR(255),
    cc_number       VARCHAR(255),
    cc_expiration   VARCHAR(255),
    cccvv           VARCHAR(255),
    placed_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT,
    CONSTRAINT pk_taco_order PRIMARY KEY (id)
);

ALTER TABLE taco_order
    ADD CONSTRAINT FK_TACO_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);



CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

INSERT INTO roles (name)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER');

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255),
    password     VARCHAR(255),
    fullname     VARCHAR(255),
    street       VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    zip          VARCHAR(255),
    phone_number VARCHAR(255),
    role_id      BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);
------


drop table taco_ingredients;
drop table ingredient;
drop table taco;
drop table taco_order;
drop table users;
drop table roles;

